# Generated by Django 4.0.3 on 2022-04-24 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('transaction_id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('leg', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('status_updated', models.DateTimeField()),
                ('status', models.CharField(max_length=80)),
                ('creator', models.CharField(max_length=80)),
                ('roster_ids', models.JSONField()),
                ('consenter_ids', models.JSONField(null=True)),
                ('adds', models.JSONField(null=True)),
                ('drops', models.JSONField(null=True)),
                ('draft_picks', models.JSONField(null=True)),
                ('waiver_budget', models.JSONField(null=True)),
                ('metadata', models.JSONField(null=True)),
                ('settings', models.JSONField(null=True)),
                ('league_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('transaction_id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('leg', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('status_updated', models.DateTimeField()),
                ('status', models.CharField(max_length=80)),
                ('creator', models.CharField(max_length=80)),
                ('roster_ids', models.JSONField()),
                ('consenter_ids', models.JSONField(null=True)),
                ('adds', models.JSONField(null=True)),
                ('drops', models.JSONField(null=True)),
                ('draft_picks', models.JSONField(null=True)),
                ('waiver_budget', models.JSONField(null=True)),
                ('metadata', models.JSONField(null=True)),
                ('settings', models.JSONField(null=True)),
                ('league_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreeAgent',
            fields=[
                ('transaction_id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('leg', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('status_updated', models.DateTimeField()),
                ('status', models.CharField(max_length=80)),
                ('creator', models.CharField(max_length=80)),
                ('roster_ids', models.JSONField()),
                ('consenter_ids', models.JSONField(null=True)),
                ('adds', models.JSONField(null=True)),
                ('drops', models.JSONField(null=True)),
                ('draft_picks', models.JSONField(null=True)),
                ('waiver_budget', models.JSONField(null=True)),
                ('metadata', models.JSONField(null=True)),
                ('settings', models.JSONField(null=True)),
                ('league_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commissioner',
            fields=[
                ('transaction_id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('leg', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('status_updated', models.DateTimeField()),
                ('status', models.CharField(max_length=80)),
                ('creator', models.CharField(max_length=80)),
                ('roster_ids', models.JSONField()),
                ('consenter_ids', models.JSONField(null=True)),
                ('adds', models.JSONField(null=True)),
                ('drops', models.JSONField(null=True)),
                ('draft_picks', models.JSONField(null=True)),
                ('waiver_budget', models.JSONField(null=True)),
                ('metadata', models.JSONField(null=True)),
                ('settings', models.JSONField(null=True)),
                ('league_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
