# Generated by Django 4.0.3 on 2022-04-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0002_alter_roster_roster_id'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissioner',
            name='roster_ids',
        ),
        migrations.AddField(
            model_name='commissioner',
            name='roster_ids',
            field=models.ManyToManyField(to='rosters.roster'),
        ),
        migrations.RemoveField(
            model_name='freeagent',
            name='roster_ids',
        ),
        migrations.AddField(
            model_name='freeagent',
            name='roster_ids',
            field=models.ManyToManyField(to='rosters.roster'),
        ),
        migrations.RemoveField(
            model_name='trade',
            name='roster_ids',
        ),
        migrations.AddField(
            model_name='trade',
            name='roster_ids',
            field=models.ManyToManyField(to='rosters.roster'),
        ),
        migrations.RemoveField(
            model_name='waiver',
            name='roster_ids',
        ),
        migrations.AddField(
            model_name='waiver',
            name='roster_ids',
            field=models.ManyToManyField(to='rosters.roster'),
        ),
    ]
