# Generated by Django 4.0.3 on 2022-04-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_commissioner_roster_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissioner',
            name='leg',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='freeagent',
            name='leg',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='leg',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='leg',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
