# Generated by Django 4.1 on 2022-08-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_player_depth_chart_order_and_more'),
        ('transactions', '0003_alter_commissioner_leg_alter_freeagent_leg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissioner',
            name='adds',
        ),
        migrations.RemoveField(
            model_name='commissioner',
            name='drops',
        ),
        migrations.AddField(
            model_name='trade',
            name='players',
            field=models.ManyToManyField(to='main.player'),
        ),
        migrations.RemoveField(
            model_name='freeagent',
            name='adds',
        ),
        migrations.RemoveField(
            model_name='freeagent',
            name='drops',
        ),
        migrations.RemoveField(
            model_name='waiver',
            name='adds',
        ),
        migrations.RemoveField(
            model_name='waiver',
            name='drops',
        ),
        migrations.AddField(
            model_name='freeagent',
            name='adds',
            field=models.ManyToManyField(related_name='fa_adds', to='main.player'),
        ),
        migrations.AddField(
            model_name='freeagent',
            name='drops',
            field=models.ManyToManyField(related_name='fa_drops', to='main.player'),
        ),
        migrations.AddField(
            model_name='waiver',
            name='adds',
            field=models.ManyToManyField(related_name='waiver_adds', to='main.player'),
        ),
        migrations.AddField(
            model_name='waiver',
            name='drops',
            field=models.ManyToManyField(related_name='waiver_drops', to='main.player'),
        ),
    ]
