# Generated by Django 4.1 on 2022-08-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_player_depth_chart_order_and_more'),
        ('transactions', '0004_remove_commissioner_adds_remove_commissioner_drops_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissioner',
            name='adds',
            field=models.ManyToManyField(related_name='commissioner_adds', to='main.player'),
        ),
        migrations.AddField(
            model_name='commissioner',
            name='drops',
            field=models.ManyToManyField(related_name='commissioner_drops', to='main.player'),
        ),
    ]
