# Generated by Django 4.1 on 2022-08-10 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_player_depth_chart_order_and_more'),
        ('transactions', '0006_alter_commissioner_creator_alter_freeagent_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissioner',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sleeperuser'),
        ),
        migrations.AlterField(
            model_name='freeagent',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sleeperuser'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sleeperuser'),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sleeperuser'),
        ),
    ]
