# Generated by Django 4.1 on 2022-08-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_commissioner_creator_alter_freeagent_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commissioner',
            old_name='creator',
            new_name='creator_id',
        ),
        migrations.RenameField(
            model_name='freeagent',
            old_name='creator',
            new_name='creator_id',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='creator',
            new_name='creator_id',
        ),
        migrations.RenameField(
            model_name='waiver',
            old_name='creator',
            new_name='creator_id',
        ),
    ]
