# Generated by Django 4.1 on 2022-08-10 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_rename_creator_commissioner_creator_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commissioner',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='freeagent',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='waiver',
            old_name='creator_id',
            new_name='creator',
        ),
    ]
