# Generated by Django 4.1 on 2022-09-10 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_sleeperuser_avatar'),
        ('transactions', '0011_alter_commissioner_creator_alter_freeagent_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissioner',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.sleeperuser'),
        ),
        migrations.AlterField(
            model_name='freeagent',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.sleeperuser'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.sleeperuser'),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.sleeperuser'),
        ),
    ]
