# Generated by Django 4.1 on 2022-09-16 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_remove_commissioner_draft_picks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissioner',
            name='waiver_budget',
        ),
        migrations.RemoveField(
            model_name='freeagent',
            name='waiver_budget',
        ),
        migrations.RemoveField(
            model_name='waiver',
            name='waiver_budget',
        ),
    ]
