# Generated by Django 4.0.3 on 2022-04-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=32, null=True)),
                ('team', models.CharField(max_length=16)),
                ('fantasy_positions', models.JSONField(null=True)),
                ('depth_chart_position', models.CharField(max_length=80, null=True)),
                ('depth_chart_order', models.IntegerField(null=True)),
                ('practice_participation', models.CharField(max_length=64, null=True)),
                ('practice_description', models.CharField(max_length=64, null=True)),
                ('injury_status', models.CharField(max_length=64, null=True)),
                ('injury_body_part', models.CharField(max_length=64, null=True)),
                ('injury_notes', models.CharField(max_length=256, null=True)),
                ('injury_date', models.DateField(null=True)),
                ('years_exp', models.IntegerField(null=True)),
                ('birth_date', models.DateField(null=True)),
                ('weight', models.CharField(max_length=4, null=True)),
                ('height', models.CharField(max_length=16, null=True)),
                ('college', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
