# Generated by Django 4.0.3 on 2022-04-24 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_player_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleeperUser',
            fields=[
                ('user_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=64)),
                ('avatar', models.CharField(max_length=64)),
                ('site_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
