# Generated by Django 4.0.3 on 2022-04-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sleeperuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleeperuser',
            name='username',
        ),
    ]
