# Generated by Django 4.0.3 on 2022-04-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_sleeperuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='depth_chart_order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='years_exp',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
