# Generated by Django 4.1 on 2022-08-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_player_depth_chart_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='search_first_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='search_last_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
