# Generated by Django 4.1 on 2022-08-17 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_player_search_first_name_player_search_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='search_first_name',
            new_name='search_full_name',
        ),
    ]
