# Generated by Django 4.1 on 2022-09-12 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_sleeperuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleeperuser',
            name='last_crawled',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
