# Generated by Django 4.1 on 2022-09-12 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_sleeperuser_last_crawled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleeperuser',
            name='last_crawled',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
