# Generated by Django 4.1 on 2022-09-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_sleeperuser_last_crawled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleeperuser',
            name='all_seasons_crawled',
            field=models.BooleanField(default=False),
        ),
    ]
