# Generated by Django 4.0.3 on 2022-04-24 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('league_id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('season', models.CharField(max_length=80)),
                ('sport', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=80)),
                ('total_rosters', models.IntegerField()),
                ('season_type', models.CharField(max_length=80)),
                ('settings', models.JSONField()),
                ('scoring_settings', models.JSONField()),
                ('roster_positions', models.JSONField()),
                ('metadata', models.JSONField()),
                ('draft_id', models.CharField(max_length=80)),
                ('bracket_id', models.IntegerField(null=True)),
                ('loser_bracket_id', models.IntegerField(null=True)),
                ('avatar', models.CharField(max_length=80, null=True)),
                ('previous_league_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
            ],
        ),
    ]
