# Generated by Django 4.0.3 on 2022-04-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='avatar',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='bracket_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='loser_bracket_id',
            field=models.IntegerField(null=True),
        ),
    ]
