# Generated by Django 4.0.3 on 2022-04-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='bracket_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='loser_bracket_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='total_rosters',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
