# Generated by Django 4.0.3 on 2022-04-18 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_alter_league_avatar_alter_league_bracket_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='previous_league_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.league'),
        ),
    ]
