# Generated by Django 4.1 on 2022-08-10 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_alter_league_bracket_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='previous_league_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_league_id', to='leagues.league'),
        ),
    ]
