# Generated by Django 4.1 on 2022-08-10 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_player_depth_chart_order_and_more'),
        ('leagues', '0003_alter_league_previous_league_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='sleeper_users',
            field=models.ManyToManyField(to='main.sleeperuser'),
        ),
        migrations.AlterField(
            model_name='league',
            name='previous_league_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.league'),
        ),
    ]
