# Generated by Django 4.1 on 2022-08-14 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_league_sleeper_users_alter_league_previous_league_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='previous_league_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_league', to='leagues.league'),
        ),
    ]
