# Generated by Django 4.1 on 2022-09-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_alter_league_previous_league_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='metadata',
            field=models.JSONField(null=True),
        ),
    ]
