# Generated by Django 4.1 on 2022-09-10 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_league_last_import_successful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='previous_league_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='following_league', to='leagues.league'),
        ),
    ]
