# Generated by Django 4.1 on 2022-09-10 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_alter_league_previous_league_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='previous_league_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='following_league', to='leagues.league'),
        ),
    ]
