# Generated by Django 4.1 on 2022-09-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0009_alter_league_previous_league_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='last_import_successful',
            field=models.BooleanField(default=False),
        ),
    ]
