# Generated by Django 4.0.3 on 2022-04-30 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rosters', '0005_roster_team_name'),
        ('leagues', '0002_alter_league_bracket_id_and_more'),
        ('main', '0005_alter_player_depth_chart_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('week', models.PositiveSmallIntegerField()),
                ('matchup_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('starters_points', models.JSONField()),
                ('players_points', models.JSONField()),
                ('points', models.FloatField()),
                ('custom_points', models.FloatField(null=True)),
                ('league_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
                ('opponent_matchup_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='matchups.matchup')),
                ('players', models.ManyToManyField(related_name='+', to='main.player')),
                ('roster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosters.roster')),
                ('starters', models.ManyToManyField(related_name='+', to='main.player')),
            ],
        ),
    ]
