# Generated by Django 4.0.3 on 2022-04-30 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0005_roster_team_name'),
        ('matchups', '0002_alter_matchup_opponent_matchup_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='opponent_matchup_id',
            field=models.OneToOneField(db_constraint=False, null=True, on_delete=django.db.models.deletion.RESTRICT, to='matchups.matchup'),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='roster_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rosters.roster'),
        ),
    ]
