# Generated by Django 4.0.3 on 2022-04-24 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('main', '0003_sleeperuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roster_id', models.IntegerField()),
                ('settings', models.JSONField()),
                ('co_owners', models.ManyToManyField(related_name='co_owners', to='main.sleeperuser')),
                ('league_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.sleeperuser')),
                ('players', models.ManyToManyField(related_name='+', to='main.player')),
                ('reserve', models.ManyToManyField(related_name='+', to='main.player')),
                ('starters', models.ManyToManyField(related_name='+', to='main.player')),
                ('taxi', models.ManyToManyField(related_name='+', to='main.player')),
            ],
            options={
                'unique_together': {('league_id', 'roster_id')},
            },
        ),
    ]
