# Generated by Django 4.0.3 on 2022-04-24 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0003_remove_roster_id_alter_roster_roster_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roster',
            unique_together=set(),
        ),
    ]
