# Generated by Django 4.0.3 on 2022-04-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0004_alter_roster_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='team_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
