# Generated by Django 4.0.3 on 2022-05-08 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_alter_league_bracket_id_and_more'),
        ('main', '0005_alter_player_depth_chart_order_and_more'),
        ('rosters', '0005_roster_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('draft_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('start_time', models.DateTimeField()),
                ('slot_to_roster_id', models.JSONField()),
                ('settings', models.JSONField()),
                ('season_type', models.CharField(max_length=32)),
                ('season', models.CharField(max_length=4)),
                ('draft_order', models.JSONField()),
                ('metadata', models.JSONField(null=True)),
                ('league_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('pick_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('round', models.PositiveSmallIntegerField()),
                ('pick_no', models.PositiveSmallIntegerField()),
                ('metadata', models.JSONField(null=True)),
                ('draft_slot', models.PositiveSmallIntegerField()),
                ('draft_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rosters.draft')),
                ('picked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.sleeperuser')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.player')),
                ('roster_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rosters.roster')),
            ],
        ),
    ]
