# Generated by Django 4.1 on 2022-09-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0006_draft_pick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
