# Generated by Django 4.1 on 2022-09-08 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_sleeperuser_avatar'),
        ('rosters', '0007_alter_draft_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.sleeperuser'),
        ),
    ]
