# Generated by Django 4.1 on 2022-09-08 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_sleeperuser_avatar'),
        ('rosters', '0008_alter_roster_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='picked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.sleeperuser'),
        ),
    ]
