# Generated by Django 4.1 on 2022-09-10 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_sleeperuser_avatar'),
        ('rosters', '0009_alter_pick_picked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='draft_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosters.draft'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='picked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.sleeperuser'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.player'),
        ),
    ]
