# Generated by Django 4.1 on 2022-09-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0010_alter_pick_draft_id_alter_pick_picked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='draft_order',
            field=models.JSONField(null=True),
        ),
    ]
