# Generated by Django 4.1 on 2022-09-10 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0011_alter_draft_draft_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='roster_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='rosters.roster'),
        ),
    ]
